### ISSUE TITLE
Masterbuilder list

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#12]
http://totalfreedom.me/masterbuilders/

It can also include the list of current masterbuilders. Right now it's more of a "download maps" web page and not "masterbuilders". 

Current list of TF master builders I know of:
- UYScutix (me :p)
- miwojedk
- Dusty01_
- DarkLynx108
- adamvandyck
- xfilez (apparently claimed to be one after Finest asked on TF forums who else is MB because he is creating a forum rank for that)
- Fluffasaurus_Rex
- AcetoneAlligator (under masterbuilder sec of the senior admin roster)

DarkLynx108 could have an extra prefix title saying "DarkLynx108 - Exec. Creative Designer"
others can just be listed as 'Master Builder'.

**Comment by OutOfYourMind** [comment]
@aggelosQQ c:
