### ISSUE TITLE
Add masterbuilder to homepage

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#14]
http://totalfreedom.me/staff

Admin Masterbuilders get the honour to show up on the staff list too at the top.

Between "TotalFreedom Developers" and "TotalFreedom Senior Admins", we can have another subtitle, "TotalFreedom Master Builders" and lists all MBs that are admins. Admin MBs get the honour of this to be first so yeah C:

**Comment by aggelosQQ** [comment]
This is something more up for debate.

**Comment by aggelosQQ** [comment]
Masterbuilders shouldn't be on the list with the Executives, they are all displayed on the masterbuilder page.
