### ISSUE TITLE
Updated Masterbuilder list idea

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#15]
http://totalfreedom.me/masterbuilders

The masterbuilder list (on that page AND staff list if included) should be the same way as the homepage of the Executive admins. Instead of a spoiler or button where you have to click it to show the list, it shows the full list at the top. Also, again like executive admin list. Each player listed as Master Builder deserve their head to be next to their name

Tools like http://i.fishbans.com/head/<username>/<size in px> can come in handy though it doesn't seem to work well with changed usernames but good for automatically updating heads.

**Comment by aggelosQQ** [comment]
The first suggestions is more up for debate.

I could implement the second one.
