### ISSUE TITLE
Masterbuilder navigation bar missing

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#16]
Where is it?? Apparently it was already added to the homepage but anyway, perhaps wasn't said properly.
Here's what I actually meant:

Where is 'MASTER BUILDERS' navigation bar?
https://i.gyazo.com/f79e1f86bd89959d7ce2eb8c993ddc1e.png

**Comment by aggelosQQ** [comment]
Right here:
https://www.screenshottr.us/v/7167b1545f711e75d4fc46831a66b8a2/10e499d8725948f6ecd06b732d39e130.png
