### ISSUE TITLE
How to apply for Admin

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#18]
_We could have a page on the website that shows information how to apply for admin, basically an online version of /ai but more detailed. :P

Here's how it could be displayed....._

**Compulsory Requirements - You must fulfill these requirements to apply:**
✓ Must have an admin recommendation.
✓ Must be registered on the forum for a minimum of 60 days if you have a Super Admin recommendation, 30 days if you have a Telnet Admin recommendation, or anytime if you have a Senior Admin recommendation.
✓ Must have filed at least 3 valid griefer reports on the forum before applying.
✓ If you are being elected under a TPAS/SPAS program, you do not have to meet any of the requirements said above.

**Secondary Requirements - Not mandatory but increases the chance of becoming an admin:**
✓ Must join an admin crew, this helps to train you whilst an Op for when you become an admin.
✓ Must be active on the server. Be active and helpful to gain more trust and recommendations!
✓ Must have made a lot of suggestions that foreshadow improvements to make the server a better place.
✓ Is an admin on one or more of our associated server, if you are an admin on other servers esp associated ones, this can show you can do your job reliably well.
✓ Is a master builder, promotional advertising and creativeness can merit the chance of becoming an administrator.

**What to do before or whilst applying**
✓ Do NOT bug admins or beg them for a recommendation, create a thread in the "Admin Information" board on the forum if you are unable to get a recommendation.
✓ Do NOT comment on your app unless asked a direct question or you disagree with someone's vote.
✓ Do NOT spam applications, lie, or copy someone else's application.
✓ Do NOT advertise your app (e.g. posting in the shoutbox), keep quiet and let the application process.
✓ DO help out a lot on the server and be active to show a reputation.
✓ DO read and memorize the conduct policy so you know the protocols right away before having the potential becoming an admin.
✓ DO memorize the admin commands from our live command help page so you know what commands to do when admin.

To apply for admin, register or join the forum:
http://totalfreedom.boards.net

Meet the requirements, then create a thread in the "Admin Applications" board with the correct template and keep quiet during the application process and follow what has been said above.

**Comment by aggelosQQ** [comment]
I couldn't find a place to add all that text, and a new page is not really worth it.
