### ISSUE TITLE
Staff Page twitter click

### ISSUE THREAD

**Issue by jjkatz** [TotalFreedom/Website#2]
Whenever you click a member since twitter was usually the case, it directs you to the top of the page rather than not having a click at all.

**Comment by aggelosQQ** [comment]
I don't really understand what you are saying, may you please explain? @jjkatz

**Comment by Telesphoreo** [comment]
If you click on any of the staff on the totalfreedom.me page, it will open a new window with the TF  page, unless the user has a Twitter account. Hes saying that it shouldn't do that or shouldn't be clickable

**Comment by aggelosQQ** [comment]
Oh, got it.
Will fix that soon.
