### ISSUE TITLE
Update my head :P

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#21]
As said, under the MB page where the masterbuilder list is. I updated my head so it shows MLG glasses, just update it. Change my head if it isn't an automatic head updater, thanks. :P

**Comment by aggelosQQ** [comment]
It's automatic.

**Comment by ghost** [comment]
doesn't work.

**Comment by aggelosQQ** [comment]
Check again later, it's not instant.

**Comment by ghost** [comment]
okay
