### ISSUE TITLE
Button image only clickable

### ISSUE THREAD

**Issue by Telesphoreo** [TotalFreedom/Website#25]
the lynx issue is fixed #24 

a screenshot is coming your way #23 

so basically the 4 buttons at the bottom, forum conduct policy, twitter, and github, you can only click on the middle or image/text it'll bring you there but if you click inside the button, but not on the image. i think it would be better if you could click on anywhere on the button and it'll be easier

**Comment by jjkatz** [comment]
Was about to make this.
