### ISSUE TITLE
Misleading title...

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#26]
On the homepage, where you can see the 'Current Staff' section, the sub-title 'Forum Moderators' is a bit misleading. It should be renamed 'Global Forum Moderators' as technically all the senior admins are moderators but the ones listed are global mods and not section mods.

Another thing:
Madgeek1450 - missing on the staff list, should include Madgeek:
"Madgeek - Co-Founder"

Madgeek (@grammarbot) is still/also a global forum moderator on the forum, so include Madgeek, forum account is not deleted (yet) due to inactivity.

**Comment by aggelosQQ** [comment]
I actually followed the senior roster, and Madgeek1450 isn't there.
