### ISSUE TITLE
Schematics tab styling

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#34]
Noticed there was no styling on: http://play.totalfreedom.me:28966/schematic/list
Maybe inherit some?

**Comment by aggelosQQ** [comment]
I'm not sure how to do that, I cannot style this page.

**Comment by TheTechPro** [comment]
Why not?

**Comment by ghost** [comment]
I see, who is in charge of it then?

**Comment by aggelosQQ** [comment]
The page is automatically generated from the TotalFreedomMod.
