### ISSUE TITLE
Masterbuilders

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#35]
Instead of going directly to a new part of the site (/masterbuilders)
I suggest you do what you did with the staff section for that part

**Comment by aggelosQQ** [comment]
What do you mean?

**Comment by ghost** [comment]
I mean that as you have done with the staff (listing most important staff members then making users click on a button to view the full list) Do the same with masterbuilders, list them on the front page then have a button like "Click to view creations"

**Comment by aggelosQQ** [comment]
I don't really see a point; I believe the masterbuilders should be listed on their own page, with their creations right below.

**Comment by ghost** [comment]
Is it really required to list every member of staff, and only the main people who actually make it run.

**Comment by aggelosQQ** [comment]
Well, yes it is kind of required as an executive requested it.
(Unless I misunderstood your comment)
