### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#36]
A new logo to fit the color scheme is needed.

**Comment by aggelosQQ** [comment]
PM me on Discord or TF's forum if you have any ideas.

**Comment by ghost** [comment]
Where would you put the logo on the site?

**Comment by aggelosQQ** [comment]
True, there's no space for a logo, which is not really necessary to my mind.

**Comment by ghost** [comment]
only place you might be able to put it is at the front in the middle of the page.above where it says "TotalFreedom has X/X players online!"

**Comment by aggelosQQ** [comment]
Possibly.

**Comment by aggelosQQ** [comment]
I'll close this as it is seems pointless to me.
