### ISSUE TITLE
Side menu closing

### ISSUE THREAD

**Issue by ghost** [TotalFreedom/Website#38]
When chosing a page in the side menu (mobile) make it so the menu closes after you have selected a page

**Comment by aggelosQQ** [comment]
Unfortunately, that is not possible.

**Comment by ghost** [comment]
Yes it is, if you send the user to that page than add a javascript that reloads the page.

**Comment by aggelosQQ** [comment]
Reloading the page doesn't really sound good to me.

**Comment by ghost** [comment]
There is a way to do this so that when you select a page it closes the menu.

**Comment by aggelosQQ** [comment]
Alright then, I'll try to find non-complicated a way, but I'm all up to merge a PR.

**Comment by Vertanzil** [comment]
#41 #42 
try that.
