### ISSUE TITLE
Low amount of players causes glitching

### ISSUE THREAD

**Issue by Telesphoreo** [TotalFreedom/Website#63]
If there are a certain amount of players, then the Why don't you join us? box glitches out.

![screen shot 2017-03-06 at 7 48 58 pm](https://cloud.githubusercontent.com/assets/7285557/23641078/43853aac-02a6-11e7-9fe3-ecff4fc406e0.jpg)

There are three players online, so the box is glitched. This doesn't happen when a lot of players are online.

**Comment by aggelosQQ** [comment]
Well that's something I never noticed and thought that I had fixed that while making it.

May you please tell me what browser you used?

**Comment by Telesphoreo** [comment]
I used Safari (desktop version, also happened a while back on mobile, but it might be fixed now)
On Thursday, March 9, 2017 at 5:21 AM aggelosQQ <notifications@github.com> wrote:

Well that's something I never noticed and thought that I had fixed that while making it.

May you please tell me what browser you used?

**Comment by aggelosQQ** [comment]
Fixed - 7cef05b
Thank you for the report!
