### ISSUE TITLE
dont see something

### ISSUE THREAD

**Issue by Barkpuppy1** [TotalFreedom/Website#65]
i dont see the status page files on this

**Comment by aggelosQQ** [comment]
It's not here.

**Comment by Barkpuppy1** [comment]
why?

**Comment by aggelosQQ** [comment]
It has nothing to do with the main TotalFreedom page (totalfreedom.me) and is not supposed to be public.

**Comment by mayokek** [comment]
If the server is offline, it should direct you to associated server list

**Comment by aggelosQQ** [comment]
That's true.
It shows a link to that status page when the server is offline.
http://totalfreedom.me/status/
