### ISSUE TITLE
Online Players Count

### ISSUE THREAD

**Issue by mayokek** [TotalFreedom/Website#7]
When I check the online players from TotalFreedom, it said 14 players and on the website, it said there is 18 players...

Does it refresh by it own?

**Comment by AvalancheYT** [comment]
Never mind, it refreshes by it own, just need to refresh the page to make it work.

**Comment by aggelosQQ** [comment]
I don't really think it updates itself, I doubt it.
You will have to reload the page.

**Comment by mayokek** [comment]
@aggelosQQ, I worded it wrong, I meant it updates when you refresh the page..

**Comment by aggelosQQ** [comment]
Oh, yeah it does.
