### ISSUE TITLE
A little spacing

### ISSUE THREAD

**Issue by Telesphoreo** [TotalFreedom/Website#78]
On my browser, between the No Imposing and Respect Privacy sections there is a little spacing that is not on any of the other sections

Here is a screenshot
![screen shot 2017-07-03 at 11 55 55 am](https://user-images.githubusercontent.com/7285557/27804958-9a023cfc-5fe6-11e7-90f5-f32a57a436f3.jpg)

**Comment by aggelosQQ** [comment]
That's odd.
That line doesn't appear to my browser - can anybody else confirm this?

**Comment by savnith** [comment]
Doesn't show in my browser.

**Comment by aggelosQQ** [comment]
I've pushed a commit that possibly fixed the issue - 3e8b871 .
I'll close this, but if it persists, please open another issue.

**Comment by Telesphoreo** [comment]
Looks better
